'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
router.use(requireAuth,requireRole(...READ));
function assertScopedIdentity(user,res){if(user.role==='GVMC_EE'&&!user.zone_id){res.status(403).json({ok:false,error:'Access denied: user has no assigned zone'});return false;}return true;}
function scope(user,params,where,alias='v'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`${alias}.zone_id=$${params.length}`);}}
router.get('/assets',async(req,res)=>{try{if(!assertScopedIdentity(req.user,res))return;const params=[],where=[];scope(req.user,params,where);if(req.query.min_risk!==undefined){const n=Number(req.query.min_risk);if(!Number.isFinite(n)||n<0||n>100)return res.status(400).json({ok:false,error:'Invalid min_risk'});params.push(n);where.push(`v.asset_graph_risk_score>=$${params.length}`);}if(req.query.band){if(!['LOW','MEDIUM','HIGH','CRITICAL'].includes(req.query.band))return res.status(400).json({ok:false,error:'Invalid risk band'});params.push(req.query.band);where.push(`v.asset_graph_risk_band=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_asset_risk_graph v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY asset_graph_risk_score DESC,v.pole_id LIMIT 5000`,params);res.json({ok:true,advisory:true,asset_risk_graph:true,data:rows});}catch(e){logger.error('Asset risk graph assets error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/assets/:poleId',async(req,res)=>{const id=Number.parseInt(req.params.poleId,10);if(!Number.isInteger(id))return res.status(400).json({ok:false,error:'Invalid pole id'});try{if(!assertScopedIdentity(req.user,res))return;const params=[id],where=['v.pole_id=$1'];scope(req.user,params,where);const row=await db.oneOrNone(`SELECT * FROM v_municipal_asset_risk_graph v WHERE ${where.join(' AND ')}`,params);if(!row)return res.status(404).json({ok:false,error:'Asset not found'});res.json({ok:true,advisory:true,asset_risk_graph:true,data:row});}catch(e){logger.error('Asset risk graph detail error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',async(req,res)=>{try{if(!assertScopedIdentity(req.user,res))return;const params=[],where=[];scope(req.user,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_asset_risk_graph_summary v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY critical_assets DESC,high_risk_assets DESC,zone_id`,params);res.json({ok:true,advisory:true,asset_risk_graph:true,data:rows});}catch(e){logger.error('Asset risk graph summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
