'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
const WRITE=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
const STATUS=['PROPOSED','UNDER_REVIEW','APPROVED','FUNDED','IN_EXECUTION','MONITORED','COMPLETED','PAUSED','REJECTED'];
const TRANSITIONS={PROPOSED:['UNDER_REVIEW','REJECTED'],UNDER_REVIEW:['APPROVED','REJECTED'],APPROVED:['FUNDED','PAUSED'],FUNDED:['IN_EXECUTION','PAUSED'],IN_EXECUTION:['MONITORED','PAUSED','COMPLETED'],MONITORED:['IN_EXECUTION','COMPLETED','PAUSED'],PAUSED:['UNDER_REVIEW','FUNDED'],COMPLETED:[],REJECTED:[]};
router.use(requireAuth);
function scope(user,params,where,alias='v'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`${alias}.zone_id=$${params.length}`);}}
router.get('/programs',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.status){if(!STATUS.includes(req.query.status))return res.status(400).json({ok:false,error:'Invalid capital program status'});params.push(req.query.status);where.push(`v.status=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_program_governance v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY proposed_amount_inr DESC,updated_at DESC LIMIT 1000`,params);res.json({ok:true,advisory:true,capital_program_governance:true,data:rows});}catch(e){logger.error('Capital program list error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_program_summary v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY program_count DESC`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Capital program summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/:capitalProgramId/events',requireRole(...READ),async(req,res)=>{try{const params=[req.params.capitalProgramId],where=['cp.capital_program_id=$1'];scope(req.user,params,where,'cp');const rows=await db.manyOrNone(`SELECT e.* FROM municipal_capital_program_events e JOIN municipal_capital_programs cp ON cp.capital_program_id=e.capital_program_id WHERE ${where.join(' AND ')} ORDER BY e.changed_at DESC`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Capital program events error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.post('/programs',requireRole(...WRITE),async(req,res)=>{try{const {program_key,title,investment_theme,proposed_amount_inr,approved_amount_inr,zone_id,plan_id,program_id,rationale,evidence_uri}=req.body;if(!program_key||!title||!investment_theme||Number(proposed_amount_inr)<0)return res.status(400).json({ok:false,error:'program_key, title, investment_theme and non-negative proposed_amount_inr are required'});if(req.user.role==='GVMC_EE'&&zone_id!==null&&zone_id!==undefined&&Number(zone_id)!==Number(req.user.zone_id))return res.status(403).json({ok:false,error:'Capital program outside your zone'});const row=await db.one(`INSERT INTO municipal_capital_programs(program_key,title,investment_theme,proposed_amount_inr,approved_amount_inr,zone_id,plan_id,program_id,rationale,evidence_uri,owner_user_id,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11) RETURNING *`,[program_key,title,investment_theme,Number(proposed_amount_inr),approved_amount_inr??null,zone_id??null,plan_id??null,program_id??null,rationale??null,evidence_uri??null,req.user.user_id]);await auditLog(req,{action:'MUNICIPAL_CAPITAL_PROGRAM_CREATED',entity_type:'municipal_capital_program',entity_id:row.capital_program_id,metadata:{program_key,zone_id:zone_id??null}});res.status(201).json({ok:true,advisory:true,data:row});}catch(e){logger.error('Capital program create error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.post('/:capitalProgramId/transition',requireRole(...WRITE),async(req,res)=>{const client=await db.connect();try{await client.query('BEGIN');const id=req.params.capitalProgramId;const current=(await client.query('SELECT * FROM municipal_capital_programs WHERE capital_program_id=$1 FOR UPDATE',[id])).rows[0];if(!current){await client.query('ROLLBACK');return res.status(404).json({ok:false,error:'Capital program not found'});}if(req.user.role==='GVMC_EE'&&current.zone_id!==req.user.zone_id){await client.query('ROLLBACK');return res.status(403).json({ok:false,error:'Capital program outside your zone'});}const to=req.body.to_status;if(!STATUS.includes(to)||!(TRANSITIONS[current.status]||[]).includes(to)){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:`Invalid transition from ${current.status} to ${to}`});}await client.query('UPDATE municipal_capital_programs SET status=$1,decision_notes=$2,approved_amount_inr=CASE WHEN $1 IN (\'APPROVED\',\'FUNDED\',\'IN_EXECUTION\',\'MONITORED\',\'COMPLETED\') THEN COALESCE($3,approved_amount_inr) ELSE approved_amount_inr END,owner_user_id=COALESCE(owner_user_id,$4) WHERE capital_program_id=$5',[to,req.body.decision_notes||null,req.body.approved_amount_inr??null,req.user.user_id,id]);await client.query('INSERT INTO municipal_capital_program_events(capital_program_id,from_status,to_status,decision_notes,evidence_uri,changed_by,metadata) VALUES($1,$2,$3,$4,$5,$6,$7)',[id,current.status,to,req.body.decision_notes||null,req.body.evidence_uri||null,req.user.user_id,req.body.metadata||{}]);await client.query('COMMIT');await auditLog(req,{action:'MUNICIPAL_CAPITAL_PROGRAM_STATUS_CHANGE',entity_type:'municipal_capital_program',entity_id:id,metadata:{from_status:current.status,to_status:to}});res.json({ok:true,advisory:true,capital_program_governance:true,capital_program_id:id,from_status:current.status,to_status:to});}catch(e){await client.query('ROLLBACK');logger.error('Capital program transition error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}finally{client.release();}});
module.exports=router;
