'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
const WRITE=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
const STATES=['PROPOSED','UNDER_REVIEW','ENDORSED','REJECTED','SUPERSEDED'];
const SCENARIOS=['CURRENT_MIX','SHIFT_TO_ASSET_RENEWAL','SHIFT_TO_NETWORK_RESILIENCE','SHIFT_TO_PREVENTIVE_MAINTENANCE','SHIFT_TO_CONTRACTOR_CAPACITY'];
router.use(requireAuth);
function scope(user,params,where,alias='v'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`(${alias}.zone_id=$${params.length} OR ${alias}.zone_id IS NULL)`);}}
router.get('/decisions',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.state){if(!STATES.includes(req.query.state))return res.status(400).json({ok:false,error:'Invalid decision state'});params.push(req.query.state);where.push(`v.decision_state=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_portfolio_decision_context v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY v.created_at DESC,v.decision_id DESC`,params);res.json({ok:true,advisory:true,capital_portfolio_decision_governance:true,data:rows});}catch(e){logger.error('Portfolio decision list error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/decision-summary',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_portfolio_decision_summary v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY v.zone_name NULLS FIRST`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Portfolio decision summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.post('/decisions',requireRole(...WRITE),async(req,res)=>{try{const {zone_id,decision_title,selected_scenario_key,decision_state='PROPOSED',decision_rationale,evidence_snapshot}=req.body;if(!decision_title||!SCENARIOS.includes(selected_scenario_key)||!STATES.includes(decision_state))return res.status(400).json({ok:false,error:'decision_title, valid selected_scenario_key and decision_state are required'});if(req.user.role==='GVMC_EE'&&zone_id!==null&&zone_id!==undefined&&Number(zone_id)!==Number(req.user.zone_id))return res.status(403).json({ok:false,error:'Decision outside your zone'});const snapshot=evidence_snapshot&&typeof evidence_snapshot==='object'?evidence_snapshot:{};const row=await db.one(`INSERT INTO municipal_capital_portfolio_decisions(zone_id,decision_title,selected_scenario_key,decision_state,decision_rationale,evidence_snapshot,decided_by,decided_at) VALUES($1,$2,$3,$4,$5,$6,$7,CASE WHEN $4 IN ('ENDORSED','REJECTED') THEN NOW() ELSE NULL END) RETURNING *`,[zone_id??null,decision_title,selected_scenario_key,decision_state,decision_rationale??null,snapshot,req.user.user_id]);await auditLog(req,{action:'CAPITAL_PORTFOLIO_DECISION_CREATED',entity_type:'municipal_capital_portfolio_decision',entity_id:row.decision_id,metadata:{zone_id:zone_id??null,selected_scenario_key,decision_state}});res.status(201).json({ok:true,advisory:true,data:row});}catch(e){logger.error('Portfolio decision create error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
