'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
const WRITE=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
const STATES=['EVIDENCE_REFRESHED','CONTEXT_CONFIRMED','REQUIRES_MORE_EVIDENCE','RETAIN_WITH_CAUTION','NO_LONGER_REUSABLE'];
router.use(requireAuth);
function assertScopedIdentity(user,res){if(user.role==='GVMC_EE'&&!user.zone_id){res.status(403).json({ok:false,error:'Access denied: user has no assigned zone'});return false;}return true;}
function scope(user,params,where,alias='v'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`(${alias}.zone_id=$${params.length} OR ${alias}.zone_id IS NULL)`);}}
router.get('/resolutions',requireRole(...READ),async(req,res)=>{try{if(!assertScopedIdentity(req.user,res))return;const params=[],where=[];scope(req.user,params,where);if(req.query.decision_id){if(!Number.isInteger(Number(req.query.decision_id)))return res.status(400).json({ok:false,error:'Invalid decision_id'});params.push(Number(req.query.decision_id));where.push(`v.decision_id=$${params.length}`);}if(req.query.review_state){if(!STATES.includes(req.query.review_state))return res.status(400).json({ok:false,error:'Invalid review state'});params.push(req.query.review_state);where.push(`v.review_state=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_decision_review_resolution v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY v.resolved_at DESC,v.resolution_id DESC LIMIT 200`,params);res.json({ok:true,human_review_only:true,data:rows,count:rows.length});}catch(e){logger.error('Capital decision resolution list error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/resolutions/latest',requireRole(...READ),async(req,res)=>{try{if(!assertScopedIdentity(req.user,res))return;const params=[],where=[];scope(req.user,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_decision_review_resolution_latest v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY v.resolved_at DESC,v.decision_id DESC`,params);res.json({ok:true,human_review_only:true,data:rows,count:rows.length});}catch(e){logger.error('Capital decision latest resolution error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.post('/resolutions',requireRole(...WRITE),async(req,res)=>{try{if(!assertScopedIdentity(req.user,res))return;const {decision_id,review_state,review_notes,evidence_snapshot}=req.body;if(!Number.isInteger(Number(decision_id))||!STATES.includes(review_state)||!review_notes||!String(review_notes).trim())return res.status(400).json({ok:false,error:'Valid decision_id, review_state and review_notes are required'});const decision=await db.oneOrNone(`SELECT decision_id,zone_id,decision_state FROM municipal_capital_portfolio_decisions WHERE decision_id=$1`,[Number(decision_id)]);if(!decision)return res.status(404).json({ok:false,error:'Capital decision not found'});if(req.user.role==='GVMC_EE'&&(decision.zone_id===null||decision.zone_id===undefined||Number(decision.zone_id)!==Number(req.user.zone_id)))return res.status(403).json({ok:false,error:'Decision outside your zone'});const snapshot=evidence_snapshot&&typeof evidence_snapshot==='object'?evidence_snapshot:{};const row=await db.one(`INSERT INTO municipal_capital_decision_review_resolutions(decision_id,review_state,review_notes,evidence_snapshot,evidence_captured_at,resolved_by,resolved_at) VALUES($1,$2,$3,$4,NOW(),$5,NOW()) RETURNING *`,[Number(decision_id),review_state,String(review_notes).trim(),snapshot,req.user.user_id]);await auditLog(req,{action:'CAPITAL_DECISION_REVIEW_RESOLVED',entity_type:'municipal_capital_decision_review_resolution',entity_id:row.resolution_id,metadata:{decision_id:Number(decision_id),review_state}});res.status(201).json({ok:true,human_review_only:true,decision_state_unchanged:true,data:row});}catch(e){logger.error('Capital decision resolution create error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
