'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
const WRITE=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
const SIGNALS=['RETAIN','REVIEW','REVISE','INSUFFICIENT_EVIDENCE'];
router.use(requireAuth);
function scope(user,params,where,alias='v'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`(${alias}.zone_id=$${params.length} OR ${alias}.zone_id IS NULL)`);}}
router.get('/patterns',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.investment_theme){params.push(req.query.investment_theme);where.push(`v.investment_theme=$${params.length}`);}if(req.query.signal){if(!SIGNALS.includes(req.query.signal))return res.status(400).json({ok:false,error:'Invalid learning signal'});params.push(req.query.signal);where.push(`v.learning_signal=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_program_learning_patterns v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY measured_programs DESC,effectiveness_rate DESC NULLS LAST`,params);res.json({ok:true,advisory:true,capital_program_learning_intelligence:true,data:rows});}catch(e){logger.error('Capital program learning patterns error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where,'v');const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_program_learning_summary v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY measured_programs DESC`,params);res.json({ok:true,advisory:true,capital_program_learning_intelligence:true,data:rows});}catch(e){logger.error('Capital program learning summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/strategy',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_program_strategy_command v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY measured_programs DESC,effectiveness_rate DESC NULLS LAST`,params);res.json({ok:true,advisory:true,capital_program_strategy_command:true,data:rows});}catch(e){logger.error('Capital program strategy command error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/evidence',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where,'v');const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_program_strategy_evidence v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY source_measured_programs_at DESC NULLS LAST,reviewed_at DESC`,params);res.json({ok:true,advisory:true,capital_program_strategy_evidence:true,data:rows});}catch(e){logger.error('Capital strategy evidence error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/effectiveness-benchmark',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where,'v');if(req.query.investment_theme){params.push(req.query.investment_theme);where.push(`v.investment_theme=$${params.length}`);}if(req.query.position){const allowed=['ABOVE_THEME_BENCHMARK','NEAR_THEME_BENCHMARK','BELOW_THEME_BENCHMARK','INSUFFICIENT_EVIDENCE'];if(!allowed.includes(req.query.position))return res.status(400).json({ok:false,error:'Invalid benchmark position'});params.push(req.query.position);where.push(`v.benchmark_position=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_investment_effectiveness_benchmark v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY effectiveness_index DESC NULLS LAST,capital_program_id`,params);res.json({ok:true,advisory:true,capital_investment_effectiveness_benchmark:true,data:rows});}catch(e){logger.error('Capital effectiveness benchmark error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/effectiveness-summary',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where,'v');const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_investment_effectiveness_summary v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY avg_effectiveness_index DESC NULLS LAST`,params);res.json({ok:true,advisory:true,capital_investment_effectiveness_summary:true,data:rows});}catch(e){logger.error('Capital effectiveness summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.post('/strategy-review',requireRole(...WRITE),async(req,res)=>{try{const {investment_theme,zone_id,strategy_signal,rationale,decision_notes,evidence_uri,metadata}=req.body||{};if(!investment_theme||!SIGNALS.includes(strategy_signal))return res.status(400).json({ok:false,error:'investment_theme and valid strategy_signal are required'});const reviewZone=zone_id===null||zone_id===undefined?null:Number(zone_id);if(req.user.role==='GVMC_EE'&&reviewZone!==null&&reviewZone!==Number(req.user.zone_id))return res.status(403).json({ok:false,error:'Strategy review outside your zone'});const pattern=await db.oneOrNone(`SELECT * FROM v_municipal_capital_program_learning_patterns WHERE investment_theme=$1 AND zone_id IS NOT DISTINCT FROM $2::int`,[investment_theme,reviewZone]);if(!pattern)return res.status(400).json({ok:false,error:'No current capital-program outcome evidence exists for this investment theme and zone'});const row=await db.one(`INSERT INTO municipal_capital_program_strategy_reviews(investment_theme,zone_id,strategy_signal,evidence_count,effectiveness_rate,avg_benefit_score,rationale,decision_notes,evidence_uri,metadata,reviewed_by,source_assessed_programs_at,source_measured_programs_at,source_delivered_programs_at,source_effectiveness_rate_at,source_avg_benefit_score_at,source_avg_health_delta_at,source_avg_reliability_delta_at,source_evidence_captured_at,evidence_state) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,NOW(),'EVIDENCE_CURRENT') RETURNING *`,[investment_theme,reviewZone,strategy_signal,pattern.assessed_programs,pattern.effectiveness_rate,pattern.avg_benefit_score,rationale||pattern.learning_rationale,decision_notes||null,evidence_uri||null,metadata||{},req.user.user_id,pattern.assessed_programs,pattern.measured_programs,pattern.delivered_programs,pattern.effectiveness_rate,pattern.avg_benefit_score,pattern.avg_health_delta,pattern.avg_reliability_delta]);await auditLog(req,{action:'MUNICIPAL_CAPITAL_PROGRAM_STRATEGY_REVIEW',entity_type:'municipal_capital_program_strategy_review',entity_id:row.review_id,metadata:{investment_theme,zone_id:reviewZone,strategy_signal,evidence_count:row.evidence_count,evidence_state:row.evidence_state}});res.status(201).json({ok:true,advisory:true,capital_program_strategy_review:true,data:row});}catch(e){logger.error('Capital program strategy review error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
