'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
const WRITE=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
const THEMES=['ASSET_RENEWAL','PREVENTIVE_MAINTENANCE','NETWORK_RESILIENCE','CONTRACTOR_CAPACITY','DATA_INFRASTRUCTURE','MIXED_CAPITAL'];
const STATUSES=['PROPOSED','UNDER_REVIEW','APPROVED','FUNDED','IN_EXECUTION','COMPLETED','PAUSED','REJECTED'];
router.use(requireAuth);
function scope(req,params,where,alias='v'){if(req.user.role==='GVMC_EE'){params.push(req.user.zone_id);where.push(`${alias}.zone_id=$${params.length}`);}}
router.get('/pipeline',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_investment_pipeline v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY capital_pressure_score DESC,high_replacement_assets DESC`,params);res.json({ok:true,advisory:true,capital_investment_intelligence:true,data:rows});}catch(e){logger.error('Capital pipeline error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',requireRole(...READ),async(req,res)=>{try{const rows=await db.manyOrNone('SELECT * FROM v_municipal_multi_year_capital_outlook ORDER BY plan_year');res.json({ok:true,advisory:true,capital_investment_intelligence:true,data:rows});}catch(e){logger.error('Capital outlook error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/command',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_capital_command v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY capital_pressure_score DESC`,params);res.json({ok:true,advisory:true,capital_investment_intelligence:true,data:rows});}catch(e){logger.error('Capital command error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/plans',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];if(req.query.status){if(!STATUSES.includes(req.query.status))return res.status(400).json({ok:false,error:'Invalid capital plan status'});params.push(req.query.status);where.push(`p.status=$${params.length}`);}if(req.query.plan_year){const year=Number(req.query.plan_year);if(!Number.isInteger(year))return res.status(400).json({ok:false,error:'Invalid plan year'});params.push(year);where.push(`p.plan_year=$${params.length}`);}if(req.user.role==='GVMC_EE'){params.push(req.user.zone_id);where.push(`p.zone_id=$${params.length}`);}const rows=await db.manyOrNone(`SELECT p.*,z.zone_name FROM municipal_capital_plans p LEFT JOIN zones z ON z.zone_id=p.zone_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY p.plan_year,p.priority_score DESC NULLS LAST,p.created_at DESC`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Capital plans error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.post('/plans',requireRole(...WRITE),async(req,res)=>{try{const {plan_year,zone_id,plan_title,investment_theme,proposed_amount_inr,priority_score,rationale,status,decision_notes,metadata}=req.body;const year=Number(plan_year);if(!Number.isInteger(year)||year<2000||year>2100||!plan_title||!THEMES.includes(investment_theme)||proposed_amount_inr===undefined)return res.status(400).json({ok:false,error:'plan_year, plan_title, investment_theme and proposed_amount_inr are required'});if(status&&!STATUSES.includes(status))return res.status(400).json({ok:false,error:'Invalid capital plan status'});if(req.user.role==='GVMC_EE'&&zone_id!==null&&zone_id!==undefined&&Number(zone_id)!==Number(req.user.zone_id))return res.status(403).json({ok:false,error:'Capital plan outside your zone'});const row=await db.one(`INSERT INTO municipal_capital_plans(plan_year,zone_id,plan_title,investment_theme,proposed_amount_inr,priority_score,rationale,status,created_by,decision_notes,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[year,zone_id??null,plan_title,investment_theme,proposed_amount_inr,priority_score??null,rationale??null,status||'PROPOSED',req.user.user_id,decision_notes??null,metadata||{}]);await auditLog(req,{action:'MUNICIPAL_CAPITAL_PLAN_CREATED',entity_type:'municipal_capital_plan',entity_id:row.plan_id,metadata:{plan_year:year,zone_id:zone_id??null,investment_theme}});res.status(201).json({ok:true,advisory:true,data:row});}catch(e){logger.error('Capital plan create error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
