'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
router.use(requireAuth,requireRole(...READ));
function scope(user,params,where,alias='v'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`${alias}.zone_id=$${params.length}`);}}
router.get('/patterns',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.pattern){if(!['SYSTEMIC','RECURRING','ISOLATED','NONE'].includes(req.query.pattern))return res.status(400).json({ok:false,error:'Invalid correlation pattern'});params.push(req.query.pattern);where.push(`v.correlation_pattern=$${params.length}`);}if(req.query.min_score!==undefined){const n=Number(req.query.min_score);if(!Number.isFinite(n)||n<0||n>100)return res.status(400).json({ok:false,error:'Invalid min_score'});params.push(n);where.push(`v.systemic_correlation_score>=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_failure_correlation_patterns v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY systemic_correlation_score DESC,pole_id LIMIT 5000`,params);res.json({ok:true,advisory:true,failure_correlation_intelligence:true,data:rows});}catch(e){logger.error('Failure correlation patterns error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/assets/:poleId',async(req,res)=>{const id=Number.parseInt(req.params.poleId,10);if(!Number.isInteger(id))return res.status(400).json({ok:false,error:'Invalid pole id'});try{const params=[id],where=['v.pole_id=$1'];scope(req.user,params,where);const row=await db.oneOrNone(`SELECT * FROM v_failure_correlation_patterns v WHERE ${where.join(' AND ')}`,params);if(!row)return res.status(404).json({ok:false,error:'Asset not found'});res.json({ok:true,advisory:true,failure_correlation_intelligence:true,data:row});}catch(e){logger.error('Failure correlation asset error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_failure_correlation_summary v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY systemic_assets DESC,high_correlation_assets DESC,zone_id`,params);res.json({ok:true,advisory:true,failure_correlation_intelligence:true,data:rows});}catch(e){logger.error('Failure correlation summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
