'use strict';
const express=require('express');
const Joi=require('joi');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ_ROLES=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','CONTRACTOR','FIELD_ENGINEER','READ_ONLY'];
const DECISION_ROLES=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
router.use(requireAuth,requireRole(...READ_ROLES));
function scope(user,params,conditions,alias='v'){
 if(user.role==='GVMC_EE'){params.push(user.zone_id);conditions.push(`${alias}.zone_id=$${params.length}`);}
 if(user.role==='CONTRACTOR'){params.push(user.contractor_id);conditions.push(`EXISTS (SELECT 1 FROM work_orders wo WHERE wo.pole_id=${alias}.pole_id AND wo.contractor_id=$${params.length})`);}
 if(user.role==='FIELD_ENGINEER'){params.push(user.user_id);conditions.push(`EXISTS (SELECT 1 FROM work_orders wo WHERE wo.pole_id=${alias}.pole_id AND wo.assigned_to=$${params.length})`);}
}
router.get('/candidates',async(req,res)=>{try{const params=[],conditions=[];scope(req.user,params,conditions);if(req.query.priority){if(!['LOW','MEDIUM','HIGH','CRITICAL'].includes(req.query.priority))return res.status(400).json({ok:false,error:'Invalid priority'});params.push(req.query.priority);conditions.push(`v.priority_score >= CASE $${params.length} WHEN 'CRITICAL' THEN 85 WHEN 'HIGH' THEN 70 WHEN 'MEDIUM' THEN 50 ELSE 0 END`);}const where=conditions.length?'WHERE '+conditions.join(' AND '):'';const rows=await db.manyOrNone(`SELECT v.*,mi.intervention_id,mi.status AS decision_status FROM v_municipal_intervention_candidates v LEFT JOIN municipal_interventions mi ON mi.pole_id=v.pole_id AND mi.status IN ('RECOMMENDED','ACKNOWLEDGED','ASSIGNED','IN_PROGRESS') ORDER BY v.priority_score DESC,v.sla_violations DESC,v.risk_score DESC LIMIT 1000`,params);res.json({ok:true,advisory:true,decision_support:true,generated_at:new Date().toISOString(),data:rows});}catch(e){logger.error('Intervention candidates error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/queue',async(req,res)=>{try{const params=[],conditions=[];scope(req.user,params,conditions,'v');const status=req.query.status;if(status){if(!['RECOMMENDED','ACKNOWLEDGED','ASSIGNED','IN_PROGRESS','COMPLETED','DEFERRED','DISMISSED'].includes(status))return res.status(400).json({ok:false,error:'Invalid status'});params.push(status);conditions.push(`mi.status=$${params.length}`);}const where=conditions.length?'WHERE '+conditions.join(' AND '):'';const rows=await db.manyOrNone(`SELECT mi.*,p.pole_number,v.health_score,v.risk_score,v.hotspot_band,v.recurrence_count_90d,v.sla_violations,v.replacement_priority FROM municipal_interventions mi LEFT JOIN poles p ON p.pole_id=mi.pole_id LEFT JOIN v_municipal_intervention_candidates v ON v.pole_id=mi.pole_id ${where} ORDER BY CASE mi.priority WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'MEDIUM' THEN 3 ELSE 4 END,mi.priority_score DESC,mi.created_at DESC LIMIT 1000`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Intervention queue error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/:id',async(req,res)=>{const id=Number.parseInt(req.params.id,10);if(!Number.isInteger(id))return res.status(400).json({ok:false,error:'Invalid intervention id'});try{const params=[id],conditions=['mi.intervention_id=$1'];if(req.user.role==='GVMC_EE'){params.push(req.user.zone_id);conditions.push(`mi.zone_id=$${params.length}`);}if(req.user.role==='CONTRACTOR'){params.push(req.user.contractor_id);conditions.push(`EXISTS (SELECT 1 FROM work_orders wo WHERE wo.pole_id=mi.pole_id AND wo.contractor_id=$${params.length})`);}if(req.user.role==='FIELD_ENGINEER'){params.push(req.user.user_id);conditions.push(`EXISTS (SELECT 1 FROM work_orders wo WHERE wo.pole_id=mi.pole_id AND wo.assigned_to=$${params.length})`);}const row=await db.oneOrNone(`SELECT mi.*,p.pole_number,v.health_score,v.health_band,v.risk_score,v.risk_band,v.hotspot_band,v.recurrence_count_90d,v.sla_violations,v.replacement_priority,v.recommendation AS generated_recommendation FROM municipal_interventions mi LEFT JOIN poles p ON p.pole_id=mi.pole_id LEFT JOIN v_municipal_intervention_candidates v ON v.pole_id=mi.pole_id WHERE ${conditions.join(' AND ')}`,params);if(!row)return res.status(404).json({ok:false,error:'Intervention not found or access denied'});res.json({ok:true,advisory:true,decision_support:true,intervention:row});}catch(e){logger.error('Intervention detail error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
const decisionSchema=Joi.object({status:Joi.string().valid('ACKNOWLEDGED','ASSIGNED','IN_PROGRESS','COMPLETED','DEFERRED','DISMISSED').required(),assigned_to:Joi.number().integer().positive().allow(null),work_order_id:Joi.number().integer().positive().allow(null),notes:Joi.string().max(4000).allow('',null)});
router.post('/:id/decision',requireRole(...DECISION_ROLES),async(req,res)=>{const id=Number.parseInt(req.params.id,10);if(!Number.isInteger(id))return res.status(400).json({ok:false,error:'Invalid intervention id'});const {error,value}=decisionSchema.validate(req.body,{abortEarly:false});if(error)return res.status(400).json({ok:false,error:error.details.map(x=>x.message).join('; ')});try{const result=await db.tx(async(t)=>{const row=await t.oneOrNone('SELECT * FROM municipal_interventions WHERE intervention_id=$1 FOR UPDATE',[id]);if(!row)throw Object.assign(new Error('NOT_FOUND'),{code:'NOT_FOUND'});if(req.user.role==='GVMC_EE'&&row.zone_id!==req.user.zone_id)throw Object.assign(new Error('FORBIDDEN'),{code:'FORBIDDEN'});if(value.assigned_to){const u=await t.oneOrNone('SELECT user_id,zone_id,is_active,role FROM users WHERE user_id=$1',[value.assigned_to]);if(!u||!u.is_active||!['FIELD_ENGINEER','GVMC_EE'].includes(u.role))throw Object.assign(new Error('Invalid assignee'),{code:'INVALID_ASSIGNEE'});if(row.zone_id!==null&&u.zone_id!==null&&u.zone_id!==row.zone_id)throw Object.assign(new Error('Assignee outside intervention zone'),{code:'INVALID_ASSIGNEE'});}if(value.work_order_id){const wo=await t.oneOrNone('SELECT work_order_id,pole_id FROM work_orders WHERE work_order_id=$1',[value.work_order_id]);if(!wo||wo.pole_id!==row.pole_id)throw Object.assign(new Error('Work order does not match intervention asset'),{code:'INVALID_WORK_ORDER'});}const updated=await t.one(`UPDATE municipal_interventions SET status=$1,assigned_to=COALESCE($2,assigned_to),work_order_id=COALESCE($3,work_order_id),acknowledged_at=CASE WHEN $1 IN ('ACKNOWLEDGED','ASSIGNED','IN_PROGRESS','COMPLETED','DEFERRED','DISMISSED') AND acknowledged_at IS NULL THEN NOW() ELSE acknowledged_at END,decided_at=NOW(),decided_by=$4,notes=COALESCE($5,notes) WHERE intervention_id=$6 RETURNING *`,[value.status,value.assigned_to??null,value.work_order_id??null,req.user.user_id,value.notes||null,id]);return {before:row,after:updated};});await auditLog(req,'MUNICIPAL_INTERVENTION_DECIDED',{intervention_id:id,from_status:result.before.status,to_status:result.after.status,assigned_to:result.after.assigned_to,work_order_id:result.after.work_order_id});res.json({ok:true,advisory:true,decision:'HUMAN_APPROVED',intervention:result.after});}catch(e){if(e.code==='NOT_FOUND')return res.status(404).json({ok:false,error:'Intervention not found'});if(e.code==='FORBIDDEN')return res.status(403).json({ok:false,error:'Access denied'});if(e.code==='INVALID_ASSIGNEE'||e.code==='INVALID_WORK_ORDER')return res.status(400).json({ok:false,error:e.message});logger.error('Intervention decision error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
