'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','CONTRACTOR','FIELD_ENGINEER','READ_ONLY'];
const WRITE=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
router.use(requireAuth,requireRole(...READ));
function scope(user,params,where,alias='v'){
 if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`${alias}.zone_id=$${params.length}`);}
 if(user.role==='CONTRACTOR'){params.push(user.contractor_id);where.push(`EXISTS(SELECT 1 FROM work_orders wo WHERE wo.pole_id=${alias}.pole_id AND wo.contractor_id=$${params.length})`);}
 if(user.role==='FIELD_ENGINEER'){params.push(user.user_id);where.push(`EXISTS(SELECT 1 FROM work_orders wo WHERE wo.pole_id=${alias}.pole_id AND wo.assigned_to=$${params.length})`);}
}
router.get('/warnings',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.severity){if(!['LOW','MEDIUM','HIGH','CRITICAL'].includes(req.query.severity))return res.status(400).json({ok:false,error:'Invalid severity'});params.push(req.query.severity);where.push(`v.severity=$${params.length}`);}const rows=await db.manyOrNone(`SELECT v.*,ra.risk_alert_id,ra.status AS alert_status FROM v_municipal_early_warnings v LEFT JOIN municipal_risk_alerts ra ON ra.pole_id=v.pole_id AND ra.risk_type='MULTI_SIGNAL' AND ra.status IN ('OPEN','ACKNOWLEDGED') ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY v.risk_score DESC LIMIT 1000`,params);res.json({ok:true,advisory:true,early_warning:true,data:rows});}catch(e){logger.error('Municipal risk warnings error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/alerts',async(req,res)=>{try{const params=[],where=[];if(req.user.role==='GVMC_EE'){params.push(req.user.zone_id);where.push(`r.zone_id=$${params.length}`);}if(req.user.role==='CONTRACTOR'){params.push(req.user.contractor_id);where.push(`EXISTS(SELECT 1 FROM work_orders wo WHERE wo.pole_id=r.pole_id AND wo.contractor_id=$${params.length})`);}if(req.user.role==='FIELD_ENGINEER'){params.push(req.user.user_id);where.push(`EXISTS(SELECT 1 FROM work_orders wo WHERE wo.pole_id=r.pole_id AND wo.assigned_to=$${params.length})`);}if(req.query.status){if(!['OPEN','ACKNOWLEDGED','RESOLVED','DISMISSED'].includes(req.query.status))return res.status(400).json({ok:false,error:'Invalid status'});params.push(req.query.status);where.push(`r.status=$${params.length}`);}const rows=await db.manyOrNone(`SELECT r.*,p.pole_number FROM municipal_risk_alerts r LEFT JOIN poles p ON p.pole_id=r.pole_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY CASE r.severity WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'MEDIUM' THEN 3 ELSE 4 END,r.risk_score DESC,r.detected_at DESC LIMIT 1000`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Municipal risk alerts error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',async(req,res)=>{try{const rows=await db.manyOrNone(`SELECT severity,COUNT(*)::int AS warning_count,COUNT(*) FILTER(WHERE open_work_orders>0)::int AS with_open_work,COUNT(*) FILTER(WHERE open_sla_exposure>0)::int AS with_sla_exposure FROM v_municipal_early_warnings GROUP BY severity ORDER BY CASE severity WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2 WHEN 'MEDIUM' THEN 3 ELSE 4 END`);res.json({ok:true,advisory:true,early_warning:true,data:rows});}catch(e){logger.error('Municipal risk summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.post('/alerts/:id/acknowledge',requireRole(...WRITE),async(req,res)=>{const id=Number.parseInt(req.params.id,10);if(!Number.isInteger(id))return res.status(400).json({ok:false,error:'Invalid risk alert id'});try{const row=await db.oneOrNone(`UPDATE municipal_risk_alerts SET status='ACKNOWLEDGED',acknowledged_at=NOW(),acknowledged_by=$1 WHERE risk_alert_id=$2 AND status='OPEN' RETURNING *`,[req.user.user_id,id]);if(!row)return res.status(404).json({ok:false,error:'Open risk alert not found'});await auditLog(req,'MUNICIPAL_RISK_ACKNOWLEDGED',{risk_alert_id:id},);res.json({ok:true,advisory:true,alert:row});}catch(e){logger.error('Municipal risk acknowledge error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
