'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
router.use(requireAuth,requireRole(...READ));
function scope(user,params,where,alias='v'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`${alias}.zone_id=$${params.length}`);}}
router.get('/topology',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.cabinet_id){const id=Number.parseInt(req.query.cabinet_id,10);if(!Number.isInteger(id))return res.status(400).json({ok:false,error:'Invalid cabinet id'});params.push(id);where.push(`v.cabinet_id=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_network_topology v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY v.zone_name,v.ward_number,v.cabinet_id,v.pole_number LIMIT 5000`,params);res.json({ok:true,advisory:true,topology:true,data:rows});}catch(e){logger.error('Network topology error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/dependencies',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.band){if(!['LOW','MEDIUM','HIGH'].includes(req.query.band))return res.status(400).json({ok:false,error:'Invalid dependency impact band'});params.push(req.query.band);where.push(`v.dependency_impact_band=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_network_dependency_impact v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY CASE v.dependency_impact_band WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 ELSE 3 END,v.affected_pct DESC LIMIT 1000`,params);res.json({ok:true,advisory:true,dependency_impact:true,data:rows});}catch(e){logger.error('Network dependency error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/cabinets/:id',async(req,res)=>{const id=Number.parseInt(req.params.id,10);if(!Number.isInteger(id))return res.status(400).json({ok:false,error:'Invalid cabinet id'});try{const params=[id];let sql=`SELECT * FROM v_network_dependency_impact WHERE cabinet_id=$1`;if(req.user.role==='GVMC_EE'){params.push(req.user.zone_id);sql+=` AND zone_id=$2`;}const summary=await db.oneOrNone(sql,params);if(!summary)return res.status(404).json({ok:false,error:'Cabinet not found or access denied'});const assetsParams=[id];let assetsSql=`SELECT * FROM v_municipal_network_topology WHERE cabinet_id=$1`;if(req.user.role==='GVMC_EE'){assetsParams.push(req.user.zone_id);assetsSql+=` AND zone_id=$2`;}const assets=await db.manyOrNone(`${assetsSql} ORDER BY pole_number`,assetsParams);res.json({ok:true,advisory:true,topology:true,summary,assets});}catch(e){logger.error('Network cabinet detail error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
