'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
const WRITE=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
const SIGNALS=['RETAIN','REVIEW','REVISE','INSUFFICIENT_EVIDENCE'];
function scope(user,params,where,alias='v'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`(${alias}.zone_id=$${params.length} OR ${alias}.zone_id IS NULL)`);}}
router.use(requireAuth);
router.get('/patterns',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.program_type){params.push(req.query.program_type);where.push(`v.program_type=$${params.length}`);}if(req.query.signal){if(!SIGNALS.includes(req.query.signal))return res.status(400).json({ok:false,error:'Invalid learning signal'});params.push(req.query.signal);where.push(`v.learning_signal=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_program_learning_patterns v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY measured_programs DESC,effectiveness_rate DESC NULLS LAST`,params);res.json({ok:true,advisory:true,program_learning_intelligence:true,data:rows});}catch(e){logger.error('Program learning patterns error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',requireRole(...READ),async(req,res)=>{try{const rows=await db.manyOrNone('SELECT * FROM v_municipal_program_learning_summary ORDER BY measured_programs DESC');res.json({ok:true,advisory:true,program_learning_intelligence:true,data:rows});}catch(e){logger.error('Program learning summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/strategy',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_program_strategy_command v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY measured_programs DESC,effectiveness_rate DESC NULLS LAST`,params);res.json({ok:true,advisory:true,municipal_program_strategy_command:true,data:rows});}catch(e){logger.error('Program strategy command error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.post('/strategy-review',requireRole(...WRITE),async(req,res)=>{try{const {program_type,zone_id,strategy_signal,evidence_count,effectiveness_rate,avg_benefit_score,rationale,decision_notes,evidence_uri,metadata}=req.body;if(!program_type||!SIGNALS.includes(strategy_signal))return res.status(400).json({ok:false,error:'program_type and valid strategy_signal are required'});if(req.user.role==='GVMC_EE'&&zone_id!==null&&zone_id!==undefined&&Number(zone_id)!==Number(req.user.zone_id))return res.status(403).json({ok:false,error:'Strategy review outside your zone'});const row=await db.one(`INSERT INTO municipal_program_strategy_reviews(program_type,zone_id,strategy_signal,evidence_count,effectiveness_rate,avg_benefit_score,rationale,decision_notes,evidence_uri,metadata,reviewed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[program_type,zone_id??null,strategy_signal,evidence_count??0,effectiveness_rate??null,avg_benefit_score??null,rationale??null,decision_notes??null,evidence_uri??null,metadata||{},req.user.user_id]);await auditLog(req,{action:'MUNICIPAL_PROGRAM_STRATEGY_REVIEW',entity_type:'municipal_program_strategy_review',entity_id:row.review_id,metadata:{program_type,zone_id:zone_id??null,strategy_signal}});res.status(201).json({ok:true,advisory:true,program_strategy_review:true,data:row});}catch(e){logger.error('Program strategy review error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
