'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
const WRITE=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
const STATUSES=['PROPOSED','UNDER_REVIEW','APPROVED','ACTIVE','MONITORED','COMPLETED','PAUSED','REJECTED'];
const TRANSITIONS={PROPOSED:['UNDER_REVIEW','REJECTED'],UNDER_REVIEW:['APPROVED','REJECTED'],APPROVED:['ACTIVE','PAUSED'],ACTIVE:['MONITORED','PAUSED','COMPLETED'],MONITORED:['ACTIVE','COMPLETED','PAUSED'],PAUSED:['UNDER_REVIEW','ACTIVE'],COMPLETED:[],REJECTED:[]};
function scoped(user,params,where,alias='p'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`${alias}.zone_id=$${params.length}`);}}
router.use(requireAuth);
router.get('/programs',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scoped(req.user,params,where);if(req.query.status){if(!STATUSES.includes(req.query.status))return res.status(400).json({ok:false,error:'Invalid program status'});params.push(req.query.status);where.push(`p.status=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_program_lifecycle p ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY priority_score DESC NULLS LAST,updated_at DESC LIMIT 1000`,params);res.json({ok:true,advisory:true,program_governance:true,data:rows});}catch(e){logger.error('Program lifecycle list error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scoped(req.user,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_program_lifecycle_summary p ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY avg_priority_score DESC NULLS LAST`,params);res.json({ok:true,advisory:true,program_governance:true,data:rows});}catch(e){logger.error('Program lifecycle summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/:programId/events',requireRole(...READ),async(req,res)=>{try{const params=[req.params.programId],where=['p.program_id=$1'];scoped(req.user,params,where);const rows=await db.manyOrNone(`SELECT e.* FROM municipal_program_events e JOIN municipal_programs p ON p.program_id=e.program_id WHERE ${where.join(' AND ')} ORDER BY e.changed_at DESC`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Program lifecycle events error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.post('/:programId/transition',requireRole(...WRITE),async(req,res)=>{const client=await db.connect();try{const id=req.params.programId;await client.query('BEGIN');const current=(await client.query('SELECT * FROM municipal_programs WHERE program_id=$1 FOR UPDATE',[id])).rows[0];if(!current){await client.query('ROLLBACK');return res.status(404).json({ok:false,error:'Program not found'});}if(req.user.role==='GVMC_EE'&&current.zone_id!==req.user.zone_id){await client.query('ROLLBACK');return res.status(403).json({ok:false,error:'Program outside your zone'});}const to=req.body.to_status;if(!STATUSES.includes(to)||!(TRANSITIONS[current.status]||[]).includes(to)){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:`Invalid transition from ${current.status} to ${to}`});}const notes=req.body.decision_notes||null;await client.query('UPDATE municipal_programs SET status=$1,decision_notes=$2,owner_user_id=COALESCE(owner_user_id,$3),actual_end_date=CASE WHEN $1=\'COMPLETED\' THEN CURRENT_DATE ELSE actual_end_date END WHERE program_id=$4',[to,notes,req.user.user_id,id]);await client.query('INSERT INTO municipal_program_events(program_id,from_status,to_status,event_type,decision_notes,evidence_uri,changed_by,metadata) VALUES($1,$2,$3,\'STATUS_CHANGE\',$4,$5,$6,$7)',[id,current.status,to,notes,req.body.evidence_uri||null,req.user.user_id,req.body.metadata||{}]);await client.query('COMMIT');await auditLog(req,{action:'MUNICIPAL_PROGRAM_STATUS_CHANGE',entity_type:'municipal_program',entity_id:id,metadata:{from_status:current.status,to_status:to}});res.json({ok:true,advisory:true,program_governance:true,program_id:id,from_status:current.status,to_status:to});}catch(e){await client.query('ROLLBACK');logger.error('Program lifecycle transition error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}finally{client.release();}});
module.exports=router;
