'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
router.use(requireAuth,requireRole(...READ));
function scope(user,params,where,alias='v'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`${alias}.zone_id=$${params.length}`);}}
router.get('/programs',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.type){params.push(req.query.type);where.push(`v.program_type=$${params.length}`);}if(req.query.review){const allowed=['IMMEDIATE_PORTFOLIO_REVIEW','HIGH_PORTFOLIO_REVIEW','PLANNING_PORTFOLIO_REVIEW','ROUTINE_PORTFOLIO_REVIEW'];if(!allowed.includes(req.query.review))return res.status(400).json({ok:false,error:'Invalid portfolio review state'});params.push(req.query.review);where.push(`v.portfolio_review_state=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_program_portfolio v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY program_priority_score DESC,critical_exposure_30d DESC LIMIT 2000`,params);res.json({ok:true,advisory:true,program_portfolio_intelligence:true,data:rows});}catch(e){logger.error('Program portfolio error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_program_portfolio_summary v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY max_program_priority_score DESC,critical_exposure_30d DESC`,params);res.json({ok:true,advisory:true,program_portfolio_intelligence:true,data:rows});}catch(e){logger.error('Program portfolio summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/command',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.band){const allowed=['IMMEDIATE','HIGH','PLANNING','ROUTINE'];if(!allowed.includes(req.query.band))return res.status(400).json({ok:false,error:'Invalid command review band'});params.push(req.query.band);where.push(`v.command_review_band=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_program_portfolio_command v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY max_priority_score DESC,critical_exposure_30d DESC`,params);res.json({ok:true,advisory:true,municipal_program_portfolio_command:true,data:rows});}catch(e){logger.error('Program portfolio command error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
