'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
const WRITE=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
const STATUSES=['PROPOSED','UNDER_REVIEW','APPROVED','ACTIVE','MONITORED','COMPLETED','PAUSED','REJECTED'];
const SOURCE_TYPES=['MANUAL','PORTFOLIO'];
const TRANSITIONS={PROPOSED:['UNDER_REVIEW','REJECTED'],UNDER_REVIEW:['APPROVED','REJECTED'],APPROVED:['ACTIVE','PAUSED'],ACTIVE:['MONITORED','PAUSED','COMPLETED'],MONITORED:['ACTIVE','COMPLETED','PAUSED'],PAUSED:['UNDER_REVIEW','ACTIVE'],COMPLETED:[],REJECTED:[]};
function scoped(user,params,where,alias='p'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`${alias}.zone_id=$${params.length}`);}}
router.use(requireAuth);

router.get('/programs',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scoped(req.user,params,where);if(req.query.status){if(!STATUSES.includes(req.query.status))return res.status(400).json({ok:false,error:'Invalid program status'});params.push(req.query.status);where.push(`p.status=$${params.length}`);}if(req.query.source_type){if(!SOURCE_TYPES.includes(req.query.source_type))return res.status(400).json({ok:false,error:'Invalid source type'});params.push(req.query.source_type);where.push(`p.source_type=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_program_lifecycle p ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY priority_score DESC NULLS LAST,updated_at DESC LIMIT 1000`,params);res.json({ok:true,advisory:true,program_governance:true,data:rows});}catch(e){logger.error('Program lifecycle list error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});

router.get('/summary',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scoped(req.user,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_program_lifecycle_summary p ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY avg_priority_score DESC NULLS LAST`,params);res.json({ok:true,advisory:true,program_governance:true,data:rows});}catch(e){logger.error('Program lifecycle summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});

// Human registration point: a governed program may be registered from a portfolio candidate,
// or explicitly as MANUAL with a recorded reason. Portfolio intelligence never auto-creates programs.
router.post('/programs',requireRole(...WRITE),async(req,res)=>{const client=await db.connect();try{const b=req.body||{};const sourceType=b.source_type||'MANUAL';if(!SOURCE_TYPES.includes(sourceType))return res.status(400).json({ok:false,error:'Invalid source_type'});if(!b.program_type||!b.program_key||!b.title)return res.status(400).json({ok:false,error:'program_type, program_key and title are required'});const priority=b.priority_score===undefined||b.priority_score===null?null:Number(b.priority_score);if(priority!==null&&(!Number.isFinite(priority)||priority<0||priority>100))return res.status(400).json({ok:false,error:'priority_score must be between 0 and 100'});if(sourceType==='MANUAL'&&!String(b.registration_notes||'').trim())return res.status(400).json({ok:false,error:'registration_notes is required for MANUAL programs'});const portfolio=b.portfolio||{};if(sourceType==='PORTFOLIO'&&(!portfolio.program_type||portfolio.zone_id===undefined||portfolio.zone_id===null||!portfolio.cluster_type||!portfolio.cluster_key))return res.status(400).json({ok:false,error:'PORTFOLIO programs require portfolio.program_type, zone_id, cluster_type and cluster_key'});await client.query('BEGIN');let zoneId=b.zone_id===undefined?null:b.zone_id;if(req.user.role==='GVMC_EE'){if(zoneId!==null&&Number(zoneId)!==Number(req.user.zone_id)){await client.query('ROLLBACK');return res.status(403).json({ok:false,error:'Program outside your zone'});}zoneId=Number(req.user.zone_id);}let portfolioLink=null;if(sourceType==='PORTFOLIO'){const pZone=Number(portfolio.zone_id);if(!Number.isInteger(pZone)){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:'portfolio.zone_id must be an integer'});}if(req.user.role==='GVMC_EE'&&pZone!==Number(req.user.zone_id)){await client.query('ROLLBACK');return res.status(403).json({ok:false,error:'Portfolio candidate outside your zone'});}const candidate=await client.query(`SELECT program_type,zone_id,cluster_type,cluster_key,program_priority_score,assets,portfolio_review_state FROM v_municipal_program_portfolio WHERE program_type=$1 AND zone_id=$2 AND cluster_type=$3 AND cluster_key=$4 LIMIT 1`,[portfolio.program_type,pZone,portfolio.cluster_type,portfolio.cluster_key]);if(!candidate.rows[0]){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:'Portfolio candidate not found; register only against a current intelligence candidate'});}portfolioLink={program_type:portfolio.program_type,zone_id:pZone,cluster_type:portfolio.cluster_type,cluster_key:portfolio.cluster_key,candidate:candidate.rows[0]};if(zoneId!==null&&Number(zoneId)!==pZone){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:'program zone_id must match the portfolio candidate zone_id'});}zoneId=pZone;}
const inserted=await client.query(`INSERT INTO municipal_programs(program_type,program_key,zone_id,title,objective,owner_user_id,status,priority_score,planned_start_date,target_end_date,decision_notes,metadata,created_by,source_type,portfolio_program_type,portfolio_zone_id,portfolio_cluster_type,portfolio_cluster_key,registration_notes) VALUES($1,$2,$3,$4,$5,NULL,'PROPOSED',$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING program_id`,[b.program_type,b.program_key,zoneId,b.title,b.objective||null,priority,b.planned_start_date||null,b.target_end_date||null,b.decision_notes||null,b.metadata||{},req.user.user_id,sourceType,portfolioLink?.program_type||null,portfolioLink?.zone_id||null,portfolioLink?.cluster_type||null,portfolioLink?.cluster_key||null,b.registration_notes||null]);const id=inserted.rows[0].program_id;await client.query(`INSERT INTO municipal_program_events(program_id,from_status,to_status,event_type,decision_notes,evidence_uri,changed_by,metadata) VALUES($1,NULL,'PROPOSED','PROGRAM_REGISTERED',$2,$3,$4,$5)`,[id,b.decision_notes||null,b.evidence_uri||null,req.user.user_id,{source_type:sourceType,portfolio_link:portfolioLink}]);await client.query('COMMIT');await auditLog(req,{action:'MUNICIPAL_PROGRAM_REGISTERED',entity_type:'municipal_program',entity_id:String(id),metadata:{source_type:sourceType,portfolio_link:portfolioLink?{program_type:portfolioLink.program_type,zone_id:portfolioLink.zone_id,cluster_type:portfolioLink.cluster_type,cluster_key:portfolioLink.cluster_key}:null}});res.status(201).json({ok:true,advisory:true,program_governance:true,program_id:id,status:'PROPOSED',source_type:sourceType,portfolio_link:portfolioLink});}catch(e){await client.query('ROLLBACK');if(e.code==='23505')return res.status(409).json({ok:false,error:'A program with this program_type and program_key already exists'});logger.error('Program lifecycle registration error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}finally{client.release();}});

router.get('/:programId/events',requireRole(...READ),async(req,res)=>{try{const params=[req.params.programId],where=['p.program_id=$1'];scoped(req.user,params,where);const rows=await db.manyOrNone(`SELECT e.* FROM municipal_program_events e JOIN municipal_programs p ON p.program_id=e.program_id WHERE ${where.join(' AND ')} ORDER BY e.changed_at DESC`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Program lifecycle events error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});

router.post('/:programId/transition',requireRole(...WRITE),async(req,res)=>{const client=await db.connect();try{const id=req.params.programId;await client.query('BEGIN');const current=(await client.query('SELECT * FROM municipal_programs WHERE program_id=$1 FOR UPDATE',[id])).rows[0];if(!current){await client.query('ROLLBACK');return res.status(404).json({ok:false,error:'Program not found'});}if(req.user.role==='GVMC_EE'&&current.zone_id!==req.user.zone_id){await client.query('ROLLBACK');return res.status(403).json({ok:false,error:'Program outside your zone'});}const to=req.body.to_status;if(!STATUSES.includes(to)||!(TRANSITIONS[current.status]||[]).includes(to)){await client.query('ROLLBACK');return res.status(400).json({ok:false,error:`Invalid transition from ${current.status} to ${to}`});}const notes=req.body.decision_notes||null;await client.query('UPDATE municipal_programs SET status=$1,decision_notes=$2,owner_user_id=COALESCE(owner_user_id,$3),actual_end_date=CASE WHEN $1='COMPLETED' THEN CURRENT_DATE ELSE actual_end_date END WHERE program_id=$4',[to,notes,req.user.user_id,id]);await client.query('INSERT INTO municipal_program_events(program_id,from_status,to_status,event_type,decision_notes,evidence_uri,changed_by,metadata) VALUES($1,$2,$3,\'STATUS_CHANGE\',$4,$5,$6,$7)',[id,current.status,to,notes,req.body.evidence_uri||null,req.user.user_id,req.body.metadata||{}]);await client.query('COMMIT');await auditLog(req,{action:'MUNICIPAL_PROGRAM_STATUS_CHANGE',entity_type:'municipal_program',entity_id:id,metadata:{from_status:current.status,to_status:to}});res.json({ok:true,advisory:true,program_governance:true,program_id:id,from_status:current.status,to_status:to});}catch(e){await client.query('ROLLBACK');logger.error('Program lifecycle transition error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}finally{client.release();}});
module.exports=router;
