'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
router.use(requireAuth,requireRole(...READ));
function scope(user,params,where,alias='v'){if(user.role==='GVMC_EE'){params.push(user.zone_id);where.push(`${alias}.zone_id=$${params.length}`);}}
router.get('/baseline',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_risk_scenario_baseline v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY current_command_risk_score DESC LIMIT 1000`,params);res.json({ok:true,advisory:true,scenario_intelligence:true,data:rows});}catch(e){logger.error('Risk scenario baseline error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/options',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.type){if(!['NO_ACTION','TARGETED_INTERVENTION','ACCELERATED_INTERVENTION','REPLACEMENT_PROGRAM'].includes(req.query.type))return res.status(400).json({ok:false,error:'Invalid scenario type'});params.push(req.query.type);where.push(`v.scenario_type=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_risk_scenario_options v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY estimated_risk_reduction DESC,projected_command_risk_30d LIMIT 2000`,params);res.json({ok:true,advisory:true,scenario_intelligence:true,data:rows});}catch(e){logger.error('Risk scenario options error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/command',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);if(req.query.state){if(!['STRONG_REVIEW_CANDIDATE','REVIEW_CANDIDATE','BASELINE_HIGH_EXPOSURE','MONITOR'].includes(req.query.state))return res.status(400).json({ok:false,error:'Invalid scenario review state'});params.push(req.query.state);where.push(`v.scenario_review_state=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_risk_scenario_command v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY estimated_risk_reduction DESC,projected_command_risk_30d LIMIT 1000`,params);res.json({ok:true,advisory:true,municipal_risk_scenario_command:true,data:rows});}catch(e){logger.error('Risk scenario command error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',async(req,res)=>{try{const params=[],where=[];scope(req.user,params,where);const rows=await db.manyOrNone(`SELECT scenario_type,scenario_impact_band,scenario_review_state,COUNT(*)::int AS scenarios,SUM(assets)::int AS assets,ROUND(AVG(projected_command_risk_30d),2) AS avg_projected_command_risk_30d,ROUND(SUM(estimated_risk_reduction),2) AS total_estimated_risk_reduction FROM v_municipal_risk_scenario_command v ${where.length?'WHERE '+where.join(' AND '):''} GROUP BY scenario_type,scenario_impact_band,scenario_review_state ORDER BY total_estimated_risk_reduction DESC`,params);res.json({ok:true,advisory:true,scenario_intelligence:true,data:rows});}catch(e){logger.error('Risk scenario summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
