'use strict';
const express=require('express');
const Joi=require('joi');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
router.use(requireAuth,requireRole('SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','CONTRACTOR','FIELD_ENGINEER','READ_ONLY'));
function scope(params,conditions,user,alias='v'){
 if(user.role==='GVMC_EE'){params.push(user.zone_id);conditions.push(`${alias}.zone_id=$${params.length}`);}
 if(user.role==='CONTRACTOR'){params.push(user.contractor_id);conditions.push(`EXISTS (SELECT 1 FROM work_orders wo WHERE wo.pole_id=${alias}.pole_id AND wo.contractor_id=$${params.length})`);}
 if(user.role==='FIELD_ENGINEER'){params.push(user.user_id);conditions.push(`EXISTS (SELECT 1 FROM work_orders wo WHERE wo.pole_id=${alias}.pole_id AND wo.assigned_to=$${params.length})`);}
}
router.get('/patterns',async(req,res)=>{try{const params=[],conditions=[];scope(params,conditions,req.user);const where=conditions.length?'WHERE '+conditions.join(' AND '):'';const rows=await db.manyOrNone(`SELECT v.* FROM v_incident_root_cause_patterns v ${where} ORDER BY incident_count DESC LIMIT 500`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Root cause patterns error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/assets',async(req,res)=>{try{const params=[],conditions=[];scope(params,conditions,req.user);const where=conditions.length?'WHERE '+conditions.join(' AND '):'';const rows=await db.manyOrNone(`SELECT * FROM v_asset_failure_patterns v ${where} ORDER BY fault_episodes_365d DESC,work_orders_365d DESC LIMIT 1000`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Asset failure patterns error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/incidents/:id',async(req,res)=>{try{const id=req.params.id;const row=await db.oneOrNone(`SELECT i.*,p.pole_id,p.pole_number,z.zone_id,z.zone_name FROM incidents i LEFT JOIN poles p ON p.pole_id=i.primary_asset_id LEFT JOIN junction_boxes j ON j.cabinet_id=p.cabinet_id LEFT JOIN wards w ON w.ward_id=j.ward_id LEFT JOIN zones z ON z.zone_id=w.zone_id WHERE i.incident_id=$1`,[id]);if(!row)return res.status(404).json({ok:false,error:'Incident not found'});if(req.user.role==='GVMC_EE'&&row.zone_id!==req.user.zone_id)return res.status(403).json({ok:false,error:'Access denied'});if(req.user.role==='CONTRACTOR'){const own=await db.oneOrNone('SELECT 1 FROM work_orders wo WHERE wo.pole_id=$1 AND wo.contractor_id=$2 LIMIT 1',[row.pole_id,req.user.contractor_id]);if(!own)return res.status(403).json({ok:false,error:'Access denied');} }if(req.user.role==='FIELD_ENGINEER'){const assigned=await db.oneOrNone('SELECT 1 FROM work_orders wo WHERE wo.pole_id=$1 AND wo.assigned_to=$2 LIMIT 1',[row.pole_id,req.user.user_id]);if(!assigned)return res.status(403).json({ok:false,error:'Access denied'});}const causes=await db.manyOrNone('SELECT * FROM incident_root_causes WHERE incident_id=$1 ORDER BY determined_at DESC',[id]);res.json({ok:true,advisory:true,incident:row,root_causes:causes});}catch(e){logger.error('Incident root cause detail error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
const schema=Joi.object({incident_id:Joi.string().uuid().required(),pole_id:Joi.number().integer().positive().allow(null),work_order_id:Joi.number().integer().positive().allow(null),cause_category:Joi.string().valid('ELECTRICAL','DRIVER','CABINET','CABLE','PHYSICAL_DAMAGE','ENVIRONMENTAL','INSTALLATION','MAINTENANCE','VANDALISM_THEFT','UNKNOWN','OTHER').required(),cause_code:Joi.string().max(80).allow('',null),confidence:Joi.number().min(0).max(100).allow(null),evidence:Joi.object().default({}),notes:Joi.string().max(4000).allow('',null)});
router.post('/determinations',requireRole('SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'),async(req,res)=>{const {error,value}=schema.validate(req.body,{abortEarly:false});if(error)return res.status(400).json({ok:false,error:error.details.map(x=>x.message).join('; ')});try{const incident=await db.oneOrNone(`SELECT i.incident_id,i.primary_asset_id,z.zone_id FROM incidents i LEFT JOIN poles p ON p.pole_id=i.primary_asset_id LEFT JOIN junction_boxes j ON j.cabinet_id=p.cabinet_id LEFT JOIN wards w ON w.ward_id=j.ward_id LEFT JOIN zones z ON z.zone_id=w.zone_id WHERE i.incident_id=$1`,[value.incident_id]);if(!incident)return res.status(404).json({ok:false,error:'Incident not found'});if(req.user.role==='GVMC_EE'&&incident.zone_id!==req.user.zone_id)return res.status(403).json({ok:false,error:'Access denied'});if(value.pole_id&&value.pole_id!==incident.primary_asset_id)return res.status(400).json({ok:false,error:'Pole does not match incident primary asset'});const row=await db.one(`INSERT INTO incident_root_causes(incident_id,pole_id,work_order_id,cause_category,cause_code,confidence,evidence,determination_source,determined_by,notes) VALUES($1,$2,$3,$4,$5,$6,$7,'HUMAN',$8,$9) RETURNING *`,[value.incident_id,value.pole_id||incident.primary_asset_id,value.work_order_id||null,value.cause_category,value.cause_code||null,value.confidence??null,value.evidence||{},req.user.user_id,value.notes||null]);await auditLog(req.user.user_id,'INCIDENT_ROOT_CAUSE_DETERMINED','incident_root_causes',row.root_cause_id,true,{incident_id:row.incident_id,cause_category:row.cause_category},req);res.status(201).json({ok:true,advisory:true,root_cause:row});}catch(e){logger.error('Root cause determination error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
