'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
const WRITE=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
const POLICY_STATUS=['PROPOSED','UNDER_REVIEW','ADOPTED','PAUSED','RETIRED'];
router.use(requireAuth);
function scoped(req,params,where,alias='v'){if(req.user.role==='GVMC_EE'){params.push(req.user.zone_id);where.push(`(${alias}.zone_id=$${params.length} OR ${alias}.zone_id IS NULL)`);}}
router.get('/signals',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scoped(req,params,where);if(req.query.planning_signal){params.push(req.query.planning_signal);where.push(`v.planning_signal=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_strategic_planning_signals v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY COALESCE(avg_program_priority_score,0) DESC,measured_programs DESC`,params);res.json({ok:true,advisory:true,strategic_planning_intelligence:true,data:rows});}catch(e){logger.error('Strategic planning signals error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',requireRole(...READ),async(req,res)=>{try{const rows=await db.manyOrNone('SELECT * FROM v_municipal_strategic_planning_summary ORDER BY measured_programs DESC');res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Strategic planning summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/policies',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];if(req.query.status){if(!POLICY_STATUS.includes(req.query.status))return res.status(400).json({ok:false,error:'Invalid policy status'});params.push(req.query.status);where.push(`p.status=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM municipal_strategy_policies p ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY priority_score DESC NULLS LAST,updated_at DESC`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Strategy policies error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/command',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scoped(req,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_policy_command v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY COALESCE(avg_program_priority_score,0) DESC,measured_programs DESC`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Policy command error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.post('/policies',requireRole(...WRITE),async(req,res)=>{try{const {policy_key,policy_area,title,objective,priority_score,horizon_years,status,decision_notes,evidence_uri,metadata}=req.body;if(!policy_key||!policy_area||!title)return res.status(400).json({ok:false,error:'policy_key, policy_area and title are required'});if(status&&!POLICY_STATUS.includes(status))return res.status(400).json({ok:false,error:'Invalid policy status'});const row=await db.one(`INSERT INTO municipal_strategy_policies(policy_key,policy_area,title,objective,priority_score,horizon_years,status,decision_notes,evidence_uri,metadata,created_by,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11) RETURNING *`,[policy_key,policy_area,title,objective??null,priority_score??null,horizon_years??null,status||'PROPOSED',decision_notes??null,evidence_uri??null,metadata||{},req.user.user_id]);await auditLog(req,{action:'MUNICIPAL_STRATEGY_POLICY_CREATED',entity_type:'municipal_strategy_policy',entity_id:row.policy_id,metadata:{policy_key,policy_area,status:row.status}});res.status(201).json({ok:true,advisory:true,data:row});}catch(e){logger.error('Strategy policy create error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
