'use strict';
const express=require('express');
const db=require('../../config/database');
const logger=require('../utils/logger');
const {requireAuth,requireRole,auditLog}=require('../middleware/auth');
const router=express.Router();
const READ=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE','READ_ONLY'];
const WRITE=['SUPER_ADMIN','GVMC_COMMISSIONER','GVMC_EE'];
const POLICY_STATUS=['PROPOSED','UNDER_REVIEW','ADOPTED','PAUSED','RETIRED'];
const LEARNING_SIGNALS=['RETAIN','REVIEW','REVISE','INSUFFICIENT_EVIDENCE'];
router.use(requireAuth);
function scoped(req,params,where,alias='v'){if(req.user.role==='GVMC_EE'){params.push(req.user.zone_id);where.push(`(${alias}.zone_id=$${params.length} OR ${alias}.zone_id IS NULL)`);}}
router.get('/signals',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scoped(req,params,where);if(req.query.planning_signal){params.push(req.query.planning_signal);where.push(`v.planning_signal=$${params.length}`);}const rows=await db.manyOrNone(`SELECT * FROM v_municipal_strategic_planning_signals v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY COALESCE(avg_program_priority_score,0) DESC,measured_programs DESC`,params);res.json({ok:true,advisory:true,strategic_planning_intelligence:true,data:rows});}catch(e){logger.error('Strategic planning signals error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/summary',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scoped(req,params,where,'v');const rows=await db.manyOrNone(`SELECT * FROM v_municipal_strategic_planning_summary v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY measured_programs DESC`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Strategic planning summary error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/policies',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];if(req.user.role==='GVMC_EE'){params.push(req.user.zone_id);where.push(`(p.source_zone_id=$${params.length} OR p.source_zone_id IS NULL)`);}if(req.query.status){if(!POLICY_STATUS.includes(req.query.status))return res.status(400).json({ok:false,error:'Invalid policy status'});params.push(req.query.status);where.push(`p.status=$${params.length}`);}const rows=await db.manyOrNone(`SELECT p.*,pe.evidence_state,pe.current_learning_signal,pe.current_measured_programs,pe.current_effectiveness_rate,pe.current_avg_benefit_score FROM municipal_strategy_policies p LEFT JOIN v_municipal_policy_evidence pe ON pe.policy_id=p.policy_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY p.priority_score DESC NULLS LAST,p.updated_at DESC`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Strategy policies error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.get('/command',requireRole(...READ),async(req,res)=>{try{const params=[],where=[];scoped(req,params,where);const rows=await db.manyOrNone(`SELECT * FROM v_municipal_policy_command v ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY COALESCE(avg_program_priority_score,0) DESC,measured_programs DESC`,params);res.json({ok:true,advisory:true,data:rows});}catch(e){logger.error('Policy command error',{error:e.message});res.status(500).json({ok:false,error:'Internal server error'});}});
router.post('/policies',requireRole(...WRITE),async(req,res)=>{try{const {policy_key,policy_area,title,objective,priority_score,horizon_years,status,decision_notes,evidence_uri,metadata,source_program_type,source_zone_id}=req.body;if(!policy_key||!policy_area||!title)return res.status(400).json({ok:false,error:'policy_key, policy_area and title are required'});if(status&&!POLICY_STATUS.includes(status))return res.status(400).json({ok:false,error:'Invalid policy status'});if(req.user.role==='GVMC_EE'&&source_zone_id!==null&&source_zone_id!==undefined&&Number(source_zone_id)!==Number(req.user.zone_id))return res.status(403).json({ok:false,error:'Policy evidence outside your zone'});let evidence=null;if(source_program_type){const params=[source_program_type,source_zone_id??null];evidence=await db.oneOrNone(`SELECT program_type,zone_id,measured_programs,effectiveness_rate,avg_benefit_score,learning_signal FROM v_municipal_program_learning_patterns WHERE program_type=$1 AND zone_id IS NOT DISTINCT FROM $2::int`,params);if(!evidence)return res.status(400).json({ok:false,error:'No governed program-learning evidence exists for the supplied policy source'});}const row=await db.one(`INSERT INTO municipal_strategy_policies(policy_key,policy_area,title,objective,priority_score,horizon_years,status,decision_notes,evidence_uri,metadata,created_by,updated_by,source_program_type,source_zone_id,source_learning_signal,source_evidence_count,source_avg_benefit_score,source_effectiveness_rate,evidence_captured_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$11,$12,$13,$14,$15,$16,$17,NOW()) RETURNING *`,[policy_key,policy_area,title,objective??null,priority_score??null,horizon_years??null,status||'PROPOSED',decision_notes??null,evidence_uri??null,metadata||{},req.user.user_id,source_program_type??null,source_zone_id??null,evidence?.learning_signal??null,evidence?.measured_programs??null,evidence?.avg_benefit_score??null,evidence?.effectiveness_rate??null]);await auditLog(req,{action:'MUNICIPAL_STRATEGY_POLICY_CREATED',entity_type:'municipal_strategy_policy',entity_id:row.policy_id,metadata:{policy_key,source_program_type:source_program_type??null,source_zone_id:source_zone_id??null,evidence_captured:Boolean(evidence)}});res.status(201).json({ok:true,advisory:true,data:row});}catch(e){logger.error('Strategy policy create error',{error:e.message});if(e.code==='23505')return res.status(409).json({ok:false,error:'A policy with this policy_key already exists'});res.status(500).json({ok:false,error:'Internal server error'});}});
module.exports=router;
